changelog:
  categories:
    - title: Breaking Changes
      labels: [breaking-change]
    - title: New Features
      labels: [enhancement]
    - title: Fix bug
      labels: [bug]
    - title: Maintenance
      labels: [maintenance, dependencies]
    - title: Other Changes
      labels: ["*"]
