# Documentation: .github/actions/docs/slack-notify-success.md
name: Post Message to Slack - Success
description: Post a message to Slack when the workflow succeeds

inputs:
  channel-id:
    description: Slack Channel ID
    required: true
  bot-oauth-token:
    description: Slack Bot OAuth Token
    required: true
  color:
    description: Color of the message
    required: false
    default: good
  mention-user:
    description: Mention user
    required: false
    default: ''
  title:
    description: Message title
    required: false
    default: 'workflow execution completed'
  message:
    description: Message body
    required: false
    default: 'Execution log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  thread-ts:
    description: Thread timestamp for reply
    required: false
    default: 'null'
  reply-broadcast:
    description: Whether to broadcast the reply to the channel
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - id: post-message-success
      shell: bash
      env:
        SLACK_CHANNEL_ID: ${{ inputs.channel-id }}
        SLACK_BOT_OAUTH_TOKEN: ${{ inputs.bot-oauth-token }}
        SLACK_COLOR: ${{ inputs.color }}
        SLACK_MENTION_USER: ${{ inputs.mention-user }}
        SLACK_TITLE_TEXT: ${{ inputs.title }}
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_THREAD_TS: ${{ inputs.thread-ts }}
        SLACK_REPLY_BROADCAST: ${{ inputs.reply-broadcast }}
        RUNNER_DEBUG: ${{ runner.debug }}
      run: |
        if [ "${RUNNER_DEBUG}" == "1" ]; then
          set -x
        fi
        if [ -n "${SLACK_MENTION_USER}" ]; then
          SLACK_TITLE="*SUCCESS - ${SLACK_MENTION_USER} ${SLACK_TITLE_TEXT}*"
        else
          SLACK_TITLE="*SUCCESS - ${SLACK_TITLE_TEXT}*"
        fi
        REPO_NAME="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
        REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
        SLACK_DATA=$(jq -n \
          --arg channel "${SLACK_CHANNEL_ID}" \
          --arg color "${SLACK_COLOR}" \
          --arg title "${SLACK_TITLE}" \
          --arg author_name "${REPO_NAME}" \
          --arg author_link "${REPO_URL}" \
          --arg text "${SLACK_MESSAGE}" \
          --arg thread_ts "${SLACK_THREAD_TS}" \
          --argjson reply_broadcast "${SLACK_REPLY_BROADCAST}" \
          'def base:
            {
              channel: $channel,
              attachments: [{
                fallback: $title,
                pretext: $title,
                color: $color,
                author_name: $author_name,
                author_link: $author_link,
                text: $text
              }]
            };
          if $thread_ts != "null" then
            base + {thread_ts: $thread_ts, reply_broadcast: $reply_broadcast}
          else
            base
          end')
        RESPONSE=$(curl --max-time 30 -sS -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${SLACK_BOT_OAUTH_TOKEN}" \
          -d "${SLACK_DATA}" \
          "https://slack.com/api/chat.postMessage") \
          || { echo "::error::Failed to post message to Slack (network error)"; exit 1; }
        if echo "${RESPONSE}" | grep -q '"ok":false'; then
          echo "::error::Slack API returned error: ${RESPONSE}"
          exit 1
        fi
