name: Setup Playwright
description: Setup Playwright browsers with caching

runs:
  using: 'composite'
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm exec playwright --version | sed 's/Version //')
        echo "version=$PLAYWRIGHT_VERSION" >> "$GITHUB_OUTPUT"

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

    - name: Install Playwright browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm exec playwright install --with-deps
