name: Feature Request
description: Propose a new Reusable Workflow or Composite Action, or suggest improvements
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature request. Please fill in the following information.

  - type: dropdown
    id: type
    attributes:
      label: Category
      options:
        - New Reusable Workflow
        - New Composite Action
        - Improvement to existing Workflow / Action
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Summary
      description: Describe what you would like to achieve
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed and what use cases it addresses
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Implementation
      description: Describe the implementation details if you have a specific approach in mind
      render: yaml

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you have considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other relevant information
