# Documentation: .github/actions/docs/slack-notify-failure.md
name: Post Message to Slack - Failure
description: Post a message to Slack when the workflow fails

inputs:
  webhook-url:
    description: Slack Incoming Webhook URL
    required: true
  color:
    description: Color of the message
    required: false
    default: danger
  mention-user:
    description: Mention user
    required: false
    default: ''
  title:
    description: Message title
    required: false
    default: 'workflow failed'
  message:
    description: Message body
    required: false
    default: 'Execution log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

runs:
  using: 'composite'
  steps:
    - id: post-message-failure
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        SLACK_COLOR: ${{ inputs.color }}
        SLACK_MENTION_USER: ${{ inputs.mention-user }}
        SLACK_TITLE_TEXT: ${{ inputs.title }}
        SLACK_MESSAGE: ${{ inputs.message }}
        RUNNER_DEBUG: ${{ runner.debug }}
      run: |
        if [ "${RUNNER_DEBUG}" == "1" ]; then
          set -x
        fi
        if [ -n "${SLACK_MENTION_USER}" ]; then
          SLACK_TITLE="*FAILURE - ${SLACK_MENTION_USER} ${SLACK_TITLE_TEXT}*"
        else
          SLACK_TITLE="*FAILURE - ${SLACK_TITLE_TEXT}*"
        fi
        REPO_NAME="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
        REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
        SLACK_DATA=$(jq -n \
          --arg color "${SLACK_COLOR}" \
          --arg title "${SLACK_TITLE}" \
          --arg author_name "${REPO_NAME}" \
          --arg author_link "${REPO_URL}" \
          --arg text "${SLACK_MESSAGE}" \
          '{
            attachments: [{
              fallback: $title,
              pretext: $title,
              color: $color,
              author_name: $author_name,
              author_link: $author_link,
              text: $text
            }]
          }')
        curl --max-time 30 --fail -sS -X POST \
          -H "Content-Type: application/json" \
          -d "${SLACK_DATA}" \
          "${SLACK_WEBHOOK_URL}" \
          || { echo "::error::Failed to post message to Slack"; exit 1; }
