name: Setup pnpm
description: Setup Node.js and pnpm, and install dependencies

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      name: Install pnpm
      with:
        package_json_file: package.json
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .node-version
        cache: 'pnpm'

    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: |
        echo "store-path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-store.outputs.store-path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
